---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Image Versions
description: Takes an upstream version string and returns various version types

inputs:
  upstream-version:
    description: Upstream Version
    required: true

outputs:
  is-valid-semver:
    description: If version is valid semantic versioning
    value: ${{ steps.version.outputs.is-valid-semver }}
  semantic:
    description: Semantic Version
    value: ${{ steps.version.outputs.semantic }}
  raw:
    description: Raw Version
    value: ${{ steps.version.outputs.raw }}
  upstream:
    description: Upstream Version
    value: ${{ steps.version.outputs.upstream }}

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 22.x

    - name: Install Semver
      shell: bash
      run: npm install semver

    - name: Determine Image Versions
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      id: version
      with:
        script: |
          const semver = require('semver');

          function calver() {
              const now = new Date();
              return `${now.getFullYear()}.${now.getMonth() + 1}.${now.getDate()}`;
          }

          const upstreamVersion = '${{ inputs.upstream-version }}';
          const parsedSemver = semver.coerce(upstreamVersion, { includePrerelease: true });
          const isValidSemver = parsedSemver !== null;
          const semanticVersion = parsedSemver !== null ? parsedSemver.version : calver();

          core.setOutput('is-valid-semver', isValidSemver);
          core.setOutput('semantic', semanticVersion);
          core.setOutput('upstream', upstreamVersion);
